name: 'Notion release publisher'
description: 'Publishes releases to notion'
author: 'Hubpay'

inputs:
  notion-secret:
    description: 'Secret for accessing Notion API'
    required: true
  notion-database:
    description: 'Release database'
    required: true

runs:
  using: node20
  main: dist/index.js
