name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  notion-secret:
    description: 'Secret for accessing Notion API'
    required: true
  notion-database:
    description: 'Release database'
    required: true

outputs:


runs:
  using: node20
  main: dist/index.js
