name: Release publisher

on:
  release:
    types: [published]
jobs:
  publish-notes:
    if: github.actor != 'dependabot[bot]' # to avoid running it on Dependabot PRs
    runs-on: ubuntu-latest

    steps:
      - uses: Hubpay/notion-release-publisher@main
        with:
          # See gh-action user in Connection page to re-generate credentials. Or visit https://www.notion.so/my-integrations/internal/6479b4e6f9574ff3b23c12b25b378baa
          notion-secret: ${{ secrets.NOTION_SECRET }}
          notion-database: ${{ secrets.NOTION_RELEASE_DATABASE }}

